= Resource Package

This package provides a Resource wrapper that is used with `resweave` to speed up implementation for resource objects.

== struct EasyResource

This struct encapsulates your resource object implementation and handles the basic request processing before calling
the handler functions provided by your implementation.

[source,go]
----
include::resource.go[tag=easyresource]
----


This simple example stores 'Foo' objects in memory, and provides only the `Create` and `List` functions.
[source,go]
----
// file: foo_resource.go

type Foo struct {
      ID: int      `json:"id"`
      Name: string `json:"name"`
}

type FooResource struct {
      resweave.LogHolder

      foos   []MyData
      nextID int
      mtx    sync.Mutex
}

func AddResource(server resweave.Server) {
      res := resource.NewResource("foo", &FooResource {
         LogHolder: resweave.NewLogholder("foo", nil),
         foos: make([]Foo, 0),
      })
      res.SetID(resweave.NumericID)
      return res.AddEasyResource(server)
}

func (fr *FooResource) List(_ context.Context, writer resource.ResponseWriter, _ *http.Request) {
      fr.mtx.Lock()
      defer fr.mtx.Unlock()

      if err := writer.WriteJsonResponse(http.StatusOK, fr.foos); err != nil {
         fr.NewError("List", err).Log()
      }
}

func (fr *FooResource) Create(_context.Context, writer resource.ResponseWriter, req *http.Request) {
      var input Foo
      if err := rw.UnmarshalJson(req.Body, &input); err != nil {
         fr.NewError("Create", err).Log()
         writer.WriteErrorResponse(http.StatusBadRequest, response.SvrErrorReadRequestFailed.WithError(err))
      }

      fr.mtx.Lock()
      defer fr.mtx.Unlock()

      input.ID = fr.nextID
      fr.nextID++

      fr.foos = append(fr.foos, foo)
      if err := writerWriteJsonResponse(http.StatusOK, foo); err != nil {
         fr.NewError("Create", err).Log()
      }
}
----

Since we did not implement `Fetch`, `Delete`, or `Update`, calling those REST methods will automatically return
`http.StatusMethodNotAllowed`

Once this has been registered with `resweave`, you can use http requests to list or create Foo objects:

* *List*: `request.NewGetRequest("http://test.org/foo")`
* *Create*: `request.NewPostRequest("http://test.org/foo", WithJsonBody(Foo{ID: 123, Name: "My Foo"}))`
* *Fetch*: `request.NewGetRequest("http://test.org/foo/123")`
* *Delete*: `request.NewDeleteRequest("http://test.org/foo/123")`
* *Update*: `request.NewPutRequest("http://test.org/foo/123", WithJsonBody(Foo{ID: 123, Name: "My Foo"}))`
** Note that for update, you use Put/Patch requests as desired and your resource handler's `Update()` function can check 
   the request method to determine which logic to perform.
   The `SetUpdateAcceptedMethods()` function may be of interest as this can configure the resource handler to automatically
   reject Put or Patch if you only want to support one of them.

== Non-ID methods

`List` and `Create` are considered "non-id" methods because they do not require an ID to be present in the REST specification.

== ID methods

`Fetch`, `Delete` and `Update` are "id" methods because they require a resource ID to be part of the URI.  A couple of things to
note:

1. `List` and `Fetch` differ only in that `Fetch` requires the ID in the URI.  This is a `resweave` implementation detail.
2. The handler functions receive the id as a string;  This simplifies the API considerably, but it does mean that the resource
   handler must convert from string to the appropriate ID type each time.
